language: cpp

os:
  - linux

compiler:
  # - clang # disabled clang due to missing libc++
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - g++ -v
  - sudo apt-get update
  - sudo apt-get install libboost-dev

install:
  - "cd $TRAVIS_BUILD_DIR/tests"
  - "g++ -std=c++11 -I../include *.cpp -omain -lboost_unit_test_framework"

script:
  - "cd $TRAVIS_BUILD_DIR/tests"
  - "./main"
